version: 2.1
orbs:
  node: circleci/node@4.1.0
executors:
  docker_exec:
    environment:
      IMAGE_NAME: geluk/matrix-webhook-gateway
    docker:
    - image: circleci/buildpack-deps:stretch
jobs:
  build:
    docker:
    - image: 'cimg/base:stable'
    steps:
    - checkout
    - node/install
    - run:
        name: Check Node version
        command: node --version
    - node/install-packages
    - run:
        name: Run linter
        command: npm run lint
    - run:
        name: Run tests
        command: npm run test
    - run:
        name: Build project
        command: npm run build
    - run:
        name: Package project
        command: npm run package
    - run:
        name: Compress artifacts
        command: tar -czf webhook-gateway.tar.gz ./webhook-gateway
        working_directory: ./out
    - store_artifacts:
        path: ./out/webhook-gateway.tar.gz
        destination: webhook-gateway.tar.gz
  docker_publish:
    executor: docker_exec
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build Docker image
        command: |
          docker build -t $IMAGE_NAME:latest \
          -t $IMAGE_NAME:$(./ci/tag.sh --major) \
          -t $IMAGE_NAME:$(./ci/tag.sh --minor) \
          -t $IMAGE_NAME:$(./ci/tag.sh --patch) .
    - run:
        name: Publish Docker image
        command: |
          echo "$DOCKER_HUB_PW" | docker login -u "$DOCKER_HUB_USER" --password-stdin
          docker push $IMAGE_NAME
  docker_publish_dev:
    executor: docker_exec
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build Docker image
        command: |
          docker build -t $IMAGE_NAME:dev .
    - run:
        name: Publish Docker image
        command: |
          echo "$DOCKER_HUB_PW" | docker login -u "$DOCKER_HUB_USER" --password-stdin
          docker push $IMAGE_NAME
workflows:
  node-tests:
    jobs:
    - build
  build:
    jobs:
    - build:
        filters:
          tags:
            only: /^.+/
          branches:
            ignore: /.*/
    - docker_publish:
        filters:
          tags:
            only: /^[0-9.]+$/
          branches:
            ignore: /.*/
    - docker_publish_dev:
        filters:
          branches:
            only: master
