version: "3.6"

services:
  synapse:
    image: matrixdotorg/synapse
    environment:
      - TZ=Europe/Amsterdam
      - SYNAPSE_SERVER_NAME=matrix.local
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_DIR=/config
      - SYNAPSE_DATA_DIR=/data
      - UID=${SYNAPSE_UID}
      - GID=${SYNAPSE_GID}
    volumes:
      - ./synapse-data:/data
      - ./synapse-config:/config
    ports:
      - 8008:8008
    restart: unless-stopped
  riot:
    image: vectorim/riot-web
    volumes:
      - ./riot.json:/app/config.json
    ports:
      - 8009:80
    restart: unless-stopped
