"$schema": "http://json-schema.org/draft-04/schema#"
type: object
properties:
  app_service:
    type: object
    properties:
      hs_token:
        type: string
        minLength: 1
      as_token:
        type: string
        minLength: 1
      id:
        type: string
      user_pattern:
        type: string
      sender_localpart:
        type: string
      rate_limited:
        type: boolean
      homeserver_name:
        type: string
        minLength: 1
      app_service_url:
        type: string
        minLength: 1
      homeserver_url:
        type: string
      pantalaimon_url:
        type: string
      listen_host:
        type: string
      listen_port:
        type: integer
        minimum: 1
      bot_user_name:
        type: string
      bot_avatar_url:
        type: [string, 'null']
    additionalProperties: false
    required: [ hs_token, as_token, homeserver_name, app_service_url ]
  database:
    type: object
    properties:
      driver:
        type: string
        enum: [ sqlite3, pg, mysql, oracledb, mssql ]
      connection:
        oneOf:
        - type: string
        - type: object
          properties:
            filename:
              type: string
          required: [ filename ]
          additionalProperties: false
        - type: object
          properties:
            host:
              type: string
            port:
              type: integer
              minimum: 1
            user:
              type: string
            password:
              type: string
            database:
              type: string
            tls:
              type: [ object, string, boolean ]
          required: [ host, user, password, database ]
          additionalProperties: false
    required: [ connection ]
  webhooks:
    type: object
    properties:
      listen_host:
        type: string
      listen_port:
        type: integer
        minimum: 1
      public_url:
        type: string
      plugin_directory:
        type: string
      plugin_cache_directory:
        type: string
      log_to_database:
        type: boolean
    required: [ public_url ]
    additionalProperties: false
required: [ app_service, webhooks ]
